package dev.misieur.justamaterial;

/**
 * Class generated by Byte Buddy in {@link dev.misieur.justamaterial.Agent#install()} in Bukkit's ClassLoader so it can be accessed from {@link org.bukkit.Material}
 */
@SuppressWarnings("JavadocReference")
public class GeneratedForBukkit {

    public static ClassLoader CLASSLOADER;

}
